# Generated by Django 6.0.3 on 2026-06-08 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Livro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('autor', models.CharField(max_length=100)),
                ('categoria', models.CharField(max_length=100)),
                ('ano_publicacao', models.IntegerField()),
                ('disponivel', models.BooleanField(default=True)),
            ],
        ),
    ]
